// Auto-generated from omegastrikers.wiki.gg (Awakenings + Gear). Display name -> local icon.
export const AWAKENING_ICONS: Record<string, string> = {
  "Slick Kicks": "/awakenings/SlickKicks.webp",
  "Pummelers": "/awakenings/Pummelers.png",
  "Vicious Vambrace": "/awakenings/ViciousVambrace.webp",
  "Magnetic Soles": "/awakenings/MagneticSoles.webp",
  "Siphoning Wand": "/awakenings/SiphoningWand.webp",
  "Momentum Boots": "/awakenings/MomentumBoots.webp",
  "Eject Button": "/awakenings/EjectButton.webp",
  "Strike Shot": "/awakenings/StrikeShot.webp",
  "Powerhouse Pauldrons": "/awakenings/PowerhousePauldrons.webp",
  "Aerials": "/awakenings/Aerials.webp",
  "Berserker": "/awakenings/Berserker.webp",
  "Built Different": "/awakenings/BuiltDifferent.webp",
  "Bulk Up": "/awakenings/BulkUp.webp",
  "Chronoboost": "/awakenings/Chronoboost.webp",
  "Deadeye": "/awakenings/Deadeye.webp",
  "Demolitionist": "/awakenings/Demolitionist.webp",
  "Egoist": "/awakenings/Egoist.webp",
  "Explosive Entrance": "/awakenings/ExplosiveEntrance.webp",
  "Fight or Flight": "/awakenings/FightorFlight.png",
  "Fire Up!": "/awakenings/FireUp.png",
  "Glass Cannon": "/awakenings/GlassCannon.png",
  "Heavy Impact": "/awakenings/HeavyImpact.png",
  "Hotshot": "/awakenings/Hotshot.png",
  "Knife's Edge": "/awakenings/KnifesEdge.png",
  "Might of the Colossus": "/awakenings/MightoftheColossus.png",
  "Missile Propulsion": "/awakenings/MissilePropulsion.png",
  "Omega Infused Accelerator": "/awakenings/OmegaInfusedAccelerator.png",
  "Orb Ponderer": "/awakenings/OrbPonderer.png",
  "Peak Performance": "/awakenings/PeakPerformance.png",
  "Prize Fighter": "/awakenings/PrizeFighter.png",
  "Rapid Fire": "/awakenings/RapidFire.png",
  "Recovery Drone": "/awakenings/RecoveryDrone.png",
  "Reptile Remedy": "/awakenings/ReptileRemedy.png",
  "Siege Machine": "/awakenings/SiegeMachine.png",
  "Spark of Agility": "/awakenings/SparkofAgility.png",
  "Spark of Focus": "/awakenings/SparkofFocus.png",
  "Spark of Strength": "/awakenings/SparkofStrength.png",
  "Specialized Training": "/awakenings/SpecializedTraining.png",
  "Stacks on Stacks": "/awakenings/StacksonStacks.png",
  "Stinger": "/awakenings/Stinger.png",
  "Team Player": "/awakenings/TeamPlayer.png",
  "Tempo Swing": "/awakenings/TempoSwing.png",
  "Timeless Creator": "/awakenings/TimelessCreator.png",
  "Adrenaline Rush": "/awakenings/AdrenalineRush.png",
  "Among Titans": "/awakenings/AmongTitans.png",
  "Big Fish": "/awakenings/BigFish.png",
  "Cast to Last": "/awakenings/CasttoLast.png",
  "Catalyst": "/awakenings/Catalyst.png",
  "Extra Special": "/awakenings/ExtraSpecial.png",
  "Inner Focus": "/awakenings/InnerFocus.png",
  "Monumentalist": "/awakenings/Monumentalist.png",
  "Orb Dancer": "/awakenings/OrbDancer.png",
  "Orb Replicator": "/awakenings/OrbReplicator.png",
  "One-Two Punch": "/awakenings/OneTwoPunch.png",
  "Perfect Form": "/awakenings/PerfectForm.png",
  "Primetime": "/awakenings/Primetime.png",
  "Quick Strike": "/awakenings/QuickStrike.png",
  "Rampage": "/awakenings/Rampage.png",
  "Reverberation": "/awakenings/Reverberation.png",
  "Spark of Leadership": "/awakenings/SparkofLeadership.png",
  "Spark of Resilience": "/awakenings/SparkofResilience.png",
  "Stagger Swagger": "/awakenings/StaggerSwagger.png",
  "Super Surge": "/awakenings/SuperSurge.png",
  "Twin Drive": "/awakenings/TwinDrive.png",
  "Unstoppable": "/awakenings/Unstoppable.png",
  "Ody Points": "/awakenings/OdyPoints.png",
  "Magnetized Soles": "/awakenings/MagnetizedSoles.webp"
};
